#!/usr/bin/env python3
"""
NetPulse - Network Scanner and Device Monitoring Tool
======================================================
Module: reporter.py
Description: Handles saving scan results to CSV and generating text reports.
Authors: Team NetPulse (Arjun, Priya, Karthik, Sneha)
Version: 1.0.0
"""

import csv
import os
from datetime import datetime
from typing import List, Dict


def save_to_csv(devices: List[Dict], output_dir: str = "outputs") -> str:
    """
    Saves the list of discovered devices to a CSV file.
    Filename is timestamped to avoid overwriting previous scans.

    Args:
        devices: List of device dicts from scanner.py
        output_dir: Directory where CSV files are saved

    Returns:
        Path to the saved CSV file
    """
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Generate timestamped filename
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(output_dir, f"scan_{timestamp}.csv")

    # Define CSV column headers
    fieldnames = ["ip", "mac", "hostname", "status", "method", "scan_time"]

    with open(filename, "w", newline="", encoding="utf-8") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        for device in devices:
            # Write only known fields (ignore any extra keys)
            row = {field: device.get(field, "N/A") for field in fieldnames}
            writer.writerow(row)

    print(f"\n  [✔] Results saved to: {filename}")
    return filename


def generate_report(devices: List[Dict], network: str, scan_duration: float) -> str:
    """
    Generates a human-readable text report of the scan results.
    Report includes summary stats, device table, and recommendations.

    Args:
        devices: List of discovered device dicts
        network: The network that was scanned (CIDR string)
        scan_duration: Time taken for the scan in seconds

    Returns:
        Report content as a string
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = len(devices)

    # Build the report string
    lines = []
    lines.append("=" * 65)
    lines.append("       NETPULSE - NETWORK SCAN REPORT")
    lines.append("=" * 65)
    lines.append(f"  Scan Date    : {now}")
    lines.append(f"  Network      : {network}")
    lines.append(f"  Scan Duration: {scan_duration:.2f} seconds")
    lines.append(f"  Total Devices: {total} active host(s) found")
    lines.append("=" * 65)
    lines.append("")

    if total == 0:
        lines.append("  [!] No active devices found on the network.")
        lines.append("      Check your network connection and try again.")
    else:
        # Table header
        lines.append(f"  {'#':<4} {'IP Address':<18} {'MAC Address':<20} {'Hostname':<25} {'Status'}")
        lines.append(f"  {'-'*4} {'-'*18} {'-'*20} {'-'*25} {'-'*10}")

        # Device rows
        for i, device in enumerate(devices, start=1):
            ip       = device.get("ip", "N/A")
            mac      = device.get("mac", "N/A")
            hostname = device.get("hostname", "Unknown")
            status   = device.get("status", "Unknown")

            # Truncate long hostnames for table display
            if len(hostname) > 23:
                hostname = hostname[:20] + "..."

            lines.append(f"  {i:<4} {ip:<18} {mac:<20} {hostname:<25} {status}")

        lines.append("")
        lines.append("=" * 65)
        lines.append("  SCAN SUMMARY")
        lines.append("=" * 65)
        lines.append(f"  Active Hosts  : {total}")
        lines.append(f"  With Hostname : {sum(1 for d in devices if d.get('hostname') != 'Unknown')}")
        lines.append(f"  With MAC Addr : {sum(1 for d in devices if d.get('mac') != 'N/A')}")

    lines.append("")
    lines.append("=" * 65)
    lines.append("  SECURITY RECOMMENDATIONS")
    lines.append("=" * 65)
    lines.append("  1. Review all unknown devices and verify authorization.")
    lines.append("  2. Ensure all devices have updated firmware/OS patches.")
    lines.append("  3. Disable unused network services to reduce attack surface.")
    lines.append("  4. Set up MAC address filtering on your router if possible.")
    lines.append("  5. Use network segmentation (VLANs) for sensitive devices.")
    lines.append("")
    lines.append("=" * 65)
    lines.append("  Report generated by NetPulse v1.0.0")
    lines.append("  https://github.com/your-team/NetPulse")
    lines.append("=" * 65)

    return "\n".join(lines)


def save_report(report_content: str, output_dir: str = "reports") -> str:
    """
    Saves the generated report text to a file.

    Args:
        report_content: The report string from generate_report()
        output_dir: Directory to save report files

    Returns:
        Path to the saved report file
    """
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = os.path.join(output_dir, f"report_{timestamp}.txt")

    with open(filename, "w", encoding="utf-8") as f:
        f.write(report_content)

    print(f"  [✔] Report saved to: {filename}")
    return filename


def print_report(report_content: str) -> None:
    """Prints the report to the terminal with color support (basic)."""
    print("\n" + report_content + "\n")
